apiVersion: v1
kind: Service
metadata:
  name: aws-scanner-service
spec:
  type: NodePort
  selector:
    app: aws-scanner
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
# done